# Numerical Python(Numpy) - Part 1

In [2]:
# de facto standard (사실상의 표준)
import numpy as np

In [3]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [5]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

- numpy python cheat
- pandas cheat sheet

## 1. Numpy Dimension array

In [9]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.dtype, a.shape

(dtype('float64'), (4,))

## Array shape

In [13]:
# Ventor(1차원 데이터)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [14]:
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
# Tensor(3차원 이상)
# tensor = np.array([[[],[]],[[],[]])
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [18]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [20]:
# element의 갯수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [22]:
# data type
# float32: 32bit로 표시 - single precision
# float64: 64bit로 표시 - double precision
a = np.array([1,2,3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [25]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [26]:
matrix.shape

(2, 3)

In [27]:
matrix.reshape(6,) # 튜플 표현으로 넣어 줘야 함.

array([1, 2, 3, 4, 5, 6])

In [28]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# -1은 numpy가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [31]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
matrix.reshape(3, -1).shape

(3, 2)

In [34]:
tensor.reshape(4,-1).shape

(4, 6)

In [35]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [36]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [37]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [44]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [40]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

In [42]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
matrix[0][1]

2

In [45]:
matrix[0,1]

2

In [46]:
tensor[1,1,2]

19

### slicing

In [47]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
# 5,6,7, 9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [51]:
# 1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [52]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))