# 연습문제 - numpy

In [3]:
import numpy as np

### 1. 행렬 만들기

넘파이를 사용하여 다음과 같은 행렬을 만드시오.
- 10 20 30 40
- 50 60 70 80

In [2]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 인덱싱, 슬라이싱
다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0, 1, 2, 3, 4],
                [ 5, 6, 7, 8, 9],
                [10, 11, 12, 13, 14]])



In [3]:
m = np.arange(15).reshape(3,5)

In [4]:
# 2-1 이 행렬에서 값 7 을 인덱싱한다.
# 2-2 이 행렬에서 값 14 을 인덱싱한다.
m[1,2], m[-1,-1]

(7, 14)

In [5]:
# 2-3 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [6]:
# 2-4 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

array([ 7, 12])

In [7]:
# 2-5 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 3. Boolean Indexing 
2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.


In [8]:
f = m.flatten()

In [9]:
# 3-1 이 배열에서 3의 배수를 찾아라.
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [10]:
# 3-2 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [11]:
# 3-3 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### 4.eye로 행렬 만들기
값을 직접 입력하지 말고 우측의 행렬을 만드시오.

In [12]:
np.eye(5,5,k=-1)*3 + np.eye(5,5)*2 + np.eye(5,5,k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5.Matrix operation
0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

In [4]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [5]:
# 5-1 전체의 최댓값
np.max(m)

9.9724

In [6]:
# 5-2 각 행의 합
np.sum(m, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [17]:
# 5-3 각 행의 최댓값
np.max(m, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [18]:
# 5-4 각 열의 평균
np.mean(m, axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [19]:
# 5-5 각 열의 최소값
np.min(m, axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### 6. Sorting
다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [8]:
score = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [9]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [10]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [11]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [12]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [13]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위 100번
주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.

In [14]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [15]:
np.mean(dice)

3.7