# DataFrame class

https://datascienceschool.net/01%20python/04.01%20%ED%8C%90%EB%8B%A4%EC%8A%A4%20%ED%8C%A8%ED%82%A4%EC%A7%80%EC%9D%98%20%EC%86%8C%EA%B0%9C.html

In [1]:
import numpy as np
import pandas as pd

### 생성

In [9]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [11]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df2 = pd.DataFrame(data, index=index, columns=columns)
df2

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [10]:
df.지역.values

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [12]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052])

In [13]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [14]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [15]:
# 전치
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

### 열 데이터의 갱신, 추가, 삭제

In [16]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [17]:
df['2020'] = [1, 2, 3, 4]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [18]:
del df['2020']

In [19]:
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

### 열 인덱싱

In [20]:
df['지역']  # 결과는 Series

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [21]:
df[['지역', '2015']]  # 결과는 DataFrame

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [22]:
df[['지역']]  # 결과는 DataFrame

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [23]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

### 행 인덱싱

In [24]:
df[:'서울']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [25]:
df[1:2]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [26]:
df['부산':'인천']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [27]:
df.head(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

## 개별 데이터 인덱싱
- df['열 이름']['행 이름']

In [28]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

### 연습 문제 4.1.3

In [ ]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [ ]:
# 1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [ ]:
# 2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [ ]:
# 3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [ ]:
np.mean(df.values, axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [ ]:
df['평균'] = np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

In [ ]:
# 4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 나시 계산한다.
del df['평균']
df.영어[3] = 80
df['평균'] = np.round(df.mean(axis=1), 1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [ ]:
# 5) 춘향의 점수를 데이터프레임으로
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [ ]:
# 중간에 있는 두 행 꺼내오기
df.head(3).tail(2)

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [ ]:
# 6) 향단의 점수를 시리즈로 나타낸다.
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64